"""empty message

Revision ID: 7343a53178db
Revises: 2a9064a2507c
Create Date: 2019-03-15 14:35:20.801060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7343a53178db'
down_revision = '2a9064a2507c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('officers', 'last_employment_date')
    op.drop_column('officers', 'last_employment_details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('last_employment_details', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('officers', sa.Column('last_employment_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('departments', 'is_active')
    # ### end Alembic commands ###
